(function(g){var window=this;var B3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.Ts(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},C3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},Fta=function(a,b){var c=new g.Ss;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},Gta=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];
if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var k=a[c++],l=a[c++];e=((e&7)<<18|(f&63)<<12|(k&63)<<6|l&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],k=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|k&63)}return b.join("")},Hta=function(){this.u=[];
this.o=[]},D3=function(a,b){switch(b.kind){case "asr":Ita(b,a.u);
break;default:Ita(b,a.o)}},Ita=function(a,b){g.Ya(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},E3=function(){g.A.call(this);
this.u=new Hta;this.A=[]},F3=function(a,b,c){E3.call(this,a);
this.audioTrack=c;this.o=null;this.A=b.mw},G3=function(){this.segments=[]},Jta=function(a,b){var c=g.qb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.db(a.segments,c),g.db(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.lb(a.segments,c,0,b),g.lb(a.segments,c+1,0,b)))},H3=function(a,b,c,d,e,f){g.A.call(this);
this.policy=a;this.player=b;this.P=c;this.C=d;this.B=e;this.G=f;this.I=this.player.M();this.A=new G3;this.u=this.w=this.o=null;this.F=new g.H(this.uy,1E3,this);this.events=new g.Gr(this);g.B(this,this.F);g.B(this,this.events);this.events.K(b,"SEEK_COMPLETE",this.bB);this.bB();this.uy()},Kta=function(a,b){var c=g.ox(b,a.policy,{}).kc(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.u=g.ir(c,d,3,100).then(function(e){a.ea();var f=!(a.B?e.response:e.responseText)||400<=e.status,k=g.Lx(e);k?(e=g.ox(a.w,a.policy,{}),f=a.w,g.kx(f.u,e,k),f.requestId=e.get("req_id"),Kta(a,a.w)):(f||null==a.C||(k=a.w.o[0],a.B?a.C(e.response,1E3*(k.startTime+a.player.Cb())):a.C(e.responseText,1E3*(k.startTime+a.player.Cb()))),a.w=null,a.u=null)});
a.w=b;Jta(a.A,a.w.o[0].u)},I3=function(a,b){E3.call(this,b.M());
this.ia=a;this.N=b;this.o=null;this.w=!1;this.B=g.lz(this.N.M())&&!this.ia.u},Lta=function(a,b){var c=[],d;
for(d in a.ia.o)if(a.ia.o.hasOwnProperty(d)){var e=a.ia.o[d];if(g.wL(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Ss({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Mta=function(a,b){return null!=b&&b in a.ia.o?a.ia.o[b]:null},Nta=function(a,b,c){var d=[],e;
for(e in a.ia.o)if(a.ia.o.hasOwnProperty(e)){var f=a.ia.o[e];if(g.wL(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},J3=function(a,b,c,d,e){E3.call(this,e||null);
this.videoId=b;this.Ux=d;this.B={};this.o=null;b=c||g.mq(a).hl||"";b=b.split("_").join("-");this.w=g.oq(a,{hl:b})},K3=function(a,b,c,d,e,f,k){var l={};
g.Sa(l,b);g.Sa(l,a.params);g.Sa(l,c);var m={};g.Sa(m,b.Ab);a.params.Ab&&g.Sa(m,a.params.Ab);g.Sa(m,c.Ab);l.Ab=m;g.R.call(this,{D:"div",H:"caption-window",O:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},J:[{D:"span",H:"captions-text",O:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.T=!1;this.w=a;this.ca=this.V=null;this.playerWidth=e;this.playerHeight=f;this.experiments=k;this.F=null;this.maxWidth=.96*e;this.va=.96*f;this.u=l;
this.Ea=c;this.B=this.o["captions-text"];this.Aa=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Z=d/360*16;this.type=0;this.ga=this.Z*Ota(m);a=new g.Mr(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.RK,this);a.subscribe("dragmove",this.QK,this);a.subscribe("dragend",this.OK,this);this.oa=this.ma=0;b="";this.u.windowOpacity&&(a=g.B1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":Pta[this.u.textAlign]};this.Aa&&(a["border-radius"]=b?this.ga/8+"px":"");if(this.A=2===this.w.params.o||3===this.w.params.o)b=this.element,c="vertical-rl",1===this.u.w&&(c="vertical-lr"),g.ie&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.th(b,"-o-writing-mode",c),g.th(b,"-webkit-writing-mode",c),g.th(b,"writing-mode",c),g.th(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3===this.w.params.o&&(g.th(b,"text-orientation",
""),g.th(b,"transform","rotate(180deg)"));g.th(this.element,a);switch(this.u.ag){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},Ota=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Qta=function(a,b){var c={},d=b.background?b.background:a.u.Ab.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Ab.backgroundOpacity;d=g.B1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*Ota(b)+"px";d=1;e=b.color||a.u.Ab.color;if(b.color||null!=b.textOpacity)e=g.B1(e),d=null==b.textOpacity?a.u.Ab.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.gr&&(k=e=b.gr);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.hl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Ab.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ue&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.RF&&(c.visibility="hidden");1===b.Rx&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.nz||g.oz,3===a.w.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.ff||2===b.ff||3===b.ff||4===b.ff||5===b.ff)if(g.nz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.ff){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Rta=function(a){a.F=g.pe("SPAN");
g.th(a.F,{display:"block"});g.J(a.F,"caption-visual-line");a.B.appendChild(a.F)},Sta=function(a,b){var c=g.pe("SPAN");
g.th(c,{display:"inline-block","white-space":"pre-wrap"});g.th(c,Qta(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.th(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.th(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Tta=function(a,b,c){a.T=a.T||!!c;
var d={};g.Sa(d,a.u.Ab);g.Sa(d,c||b.o);g.Sa(d,a.Ea.Ab);(c=!a.F)&&Rta(a);for(var e=a.V&&a.ca&&g.Pb(d,a.ca)?a.V:Sta(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(Rta(a),e=Sta(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.qe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.nz||!g.xh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.xh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.ke?g.th(e,m,"1em"):g.th(e,m,"0.5em")))}a.ca=d;a.V=e;a.C.push(b)},L3=function(a,b,c,d,e,f,k){K3.call(this,a,b,c,d,e,f,k);
this.type=1},M3=function(a,b,c,d,e,f,k){K3.call(this,a,b,c,d,e,f,k);
this.type=2;this.G=[];this.L=this.I=this.aa=0;this.R=NaN;this.za=0;this.Ca=null;this.da=new g.H(this.LM,433,this);g.J(this.element,"ytp-caption-window-rollup");g.B(this,this.da);g.th(this.element,"overflow","hidden")},Uta=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},Vta=function(a){if(isNaN(a.R)){var b=a.u.Zg;
if(b){var c=g.pe("SPAN");g.ze(c,"\u2013".repeat(b));g.th(c,Qta(a,a.u.Ab));a.B.appendChild(c);a.R=c.offsetWidth;a.B.removeChild(c)}else a.R=0}return a.R},Wta=function(a,b){if(!b)return"";
a.A&&1!==a.w.params.w&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},Xta=function(a){a.G=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.w.params.u,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.L=Math.max(Vta(a),a.za,Uta(a,a.B))},Yta=function(a,b){Xta(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!==a.aa){var d=0<c&&0===a.aa;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),a.da.Ua());g.th(a.B,"transform",Wta(a,c));a.aa=c}Xta(a)},N3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.kC.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=k},O3=function(a,b,c,d,e){g.kC.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Zta=function(a){var b="_"+P3++;
return new O3(0,0x8000000000000,0,b,a)},aua=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.Sb){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=$ta(l.textContent,n.textContent,p.textContent,f.textContent,k);return new N3(a,b,e,c,l,d,m)}switch(m.Sb){case 9:case 10:m.ff=1;break;case 11:m.ff=2;break;case 12:m.ff=3;break;case 13:m.ff=4;break;case 14:m.ff=5}return new N3(a,b,e,c,l.textContent||"",d,m)},$ta=function(a,b,c,d,e){var f=g.hl(),k=
f?g.pe("DIV"):g.pe("RUBY"),l=g.pe("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.pe("DIV"):g.pe("RP");a.textContent=b;k.appendChild(a);b=f?g.pe("DIV"):g.pe("RT");b.textContent=c;k.appendChild(b);c=e.Sb;if(10===c||11===c||12===c||13===c||14===c)if(g.th(b,"text-emphasis-style","filled circle"),g.th(b,"text-emphasis-color","currentcolor"),g.th(b,"webkit-text-emphasis","filled circle"),11===e.Sb||13===e.Sb)g.th(b,"webkit-text-emphasis-position","under left"),g.th(b,"text-emphasis-position","under left");c=!0;if(4===e.Sb||7===e.Sb||12===e.Sb||
14===e.Sb)g.th(k,"ruby-position","over"),g.th(k,"-webkit-ruby-position","before");else if(5===e.Sb||6===e.Sb||11===e.Sb||13===e.Sb)g.th(k,"ruby-position","under"),g.th(k,"-webkit-ruby-position","after"),c=!1;e=f?g.pe("DIV"):g.pe("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.th(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.th(f,"display","none"),f=f.nextElementSibling,g.th(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.th(k.lastElementChild,"display","none"),d?(g.th(k,"padding-top","0.6em"),g.th(f,"top","0")):(g.th(k,"padding-bottom","0.6em"),g.th(f,"bottom","0")));return k},Q3=function(){g.A.apply(this,arguments)},R3=function(a){Q3.call(this);
this.C=a;this.A={};this.I={};this.P={};this.B="_"+P3++;this.G={};this.u=this.o=null;this.F=!0},S3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},T3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},U3=function(a,b){var c=S3(a,b);
return void 0!==c?c:null},W3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return V3.test(c),c},bua=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.P[d]:a.C);d=U3(b,"mh");null!=d&&(c.Sj=d);d=U3(b,"ju");null!=d&&(c.textAlign=d);d=U3(b,"pd");null!=d&&(c.o=d);d=U3(b,"sd");null!=d&&(c.w=d);d=W3(b,"wfc");null!=d&&(c.windowColor=d);d=S3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},cua=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.I[d]);d=U3(b,"ap");null!=d&&(c.ag=d);d=S3(b,"cc");null!=d&&(c.Zg=d);d=S3(b,"ah");null!=d&&(c.Xe=d);d=S3(b,"rc");null!=d&&(c.u=d);d=S3(b,"av");null!=d&&(c.Lg=d);return c},dua=function(a,b,c,d){var e={};
g.Sa(e,cua(a,b));g.Sa(e,bua(a,b));d?g.Pb(e,a.C)?(d=a.B,e=a.C):d="_"+P3++:d=b.getAttribute("id")||"_"+P3++;a=S3(b,"t")+c;b=S3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.Zg,e.Zg=c;return new O3(a,b,0,d,e)},X3=function(a){Q3.call(this);
this.C=a;this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map},Y3=function(a){a=g.Nd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},eua=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.Zg=b);if(2===f.o||3===f.o)b=f.u,f.u=f.Zg,f.Zg=b;return new O3(c,d,0,e,f)},$3=function(){this.w=this.time=this.mode=this.u=0;
this.A=new Z3(this);this.B=new Z3(this);this.o=[];this.clear()},gua=function(a,b,c){if(255===a&&255===b||!a&&!b)return{bi:a,
Vg:b,result:0};a=fua[a];b=fua[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Vg===d;if(d)return{bi:a,Vg:b,result:1}}else if(b&128&&1<=a&&31>=a)return{bi:a,Vg:b,result:2};return{bi:a,Vg:b,result:3}},iua=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.w&&a.reset(),a.A.o.clear(),a.B.o.clear()):(a.w=0,hua(a.A,b,c,d))},jua=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.q(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?iua(a,d.ow,d.pw,b):1===d.type&&a.u&496&&hua(a.B,d.ow,d.pw,b);a.o.length=0},a4=function(){this.type=0},b4=function(){this.state=this.Vg=this.bi=0},kua=function(){this.timestamp=this.o=0},c4=function(a){this.B=a;
this.w=[];this.o=this.u=this.row=0;this.style=new a4;for(a=this.A=0;15>=a;a++){this.w[a]=[];for(var b=0;32>=b;b++)this.w[a][b]=new kua}},d4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.B.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.w[m][p];
if(0!==t.o){0===c&&(c=m,d=p);n=String.fromCharCode(t.o);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===t.o||32===p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.w[k][m],t=p.o,0!==t&&(0===c&&(c=k,d=m),n=String.fromCharCode(t),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32===m||0===t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},pua=function(a,b){switch(a){case 0:return lua[(b&127)-32];
case 1:return mua[b&15];case 2:return nua[b&31];case 3:return oua[b&31]}return 0},e4=function(a){return a.w[a.row][a.u]},f4=function(a,b,c){2<=b&&1<a.u&&(--a.u,e4(a).o=0);
var d=e4(a);d.timestamp=a.B.time+0;d.o=pua(b,c);32>a.u&&a.u++},qua=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.w[b+e][f],l=a.w[c+e][f];
k.o=l.o;k.timestamp=l.timestamp}},g4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},h4=function(a){a.row=0<a.o?a.o:1;
a.u=1;g4(a,0,15)},i4=function(a){this.w=a;
this.B=0;this.style=new a4;this.C=new c4(this.w);this.F=new c4(this.w);this.text=new c4(this.w);this.u=this.C;this.A=this.F;this.o=this.u},j4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(d4(d,c),h4(a.u),h4(a.A),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.w.mode=1<<d.A;e?d.u=1:d.o!==b&&(d.o>b?(d4(d,c),g4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},rua=function(a){a.style.set(1);
a.o=a.A;a.o.o=0;a.o.style=a.style;a.w.mode=1<<a.o.A},sua=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.w.mode=1<<a.o.A},Z3=function(a){this.u=a;
this.B=0;this.w=new i4(this.u);this.C=new i4(this.u);this.o=new b4;this.A=this.w},hua=function(a,b,c,d){a.o.update();
b=gua(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.bi;c=b.Vg;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&f4(a,0,b),c&96&&f4(a,0,c),0!==b&&0!==c&&3===a.style.type&&d4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.bi=e,b.Vg=c,b.state=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,k=1+d-c.o;qua(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));g4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:f4(b.o,0,32);break a;case 48:57===c?(d=b.o,e4(d).o=0,32>d.u&&d.u++):f4(b.o,1,c&15)}break;case 2:c&32&&f4(b.o,2,c&31);break;case 3:c&32&&f4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:rua(b);
break;case 33:d=b.o;1<d.u&&(--d.u,e4(d).o=0);break;case 36:d=b.o;b=e4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]===b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:j4(b,2,d);break;case 38:j4(b,3,d);break;case 39:j4(b,4,d);break;case 40:f4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.w.mode=1<<b.o.A;break;case 42:d=b.text;d.o=15;d.style.set(4);h4(d);sua(b);break;case 43:sua(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:d4(a,d)}g4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;d4(a,d);qua(a,b,b+1,a.o-1);g4(a,a.row,1)}break;case 46:g4(b.A,0,15);break;case 47:d4(b.u,d),b.A.updateTime(b.w.time+0),d=b.A,b.A=b.u,b.u=d,rua(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},tua=function(){},k4=function(a,b,c){this.G=a;
this.F=c;this.version=this.C=this.A=this.o=0;this.u=new DataView(this.G);this.w=[]},l4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},m4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},n4=function(a,b){Q3.call(this);
this.u=a;this.A=b;this.track="CC3"===this.A.languageName?4:0;this.o=new $3;this.o.u=1<<this.track},o4=function(a){if("string"===typeof a)return!1;
a=new k4(a,8,0);return uua(a)},uua=function(a){if(!(a.o<a.u.byteLength)||1380139777!==m4(a))return!1;
a.version=l4(a);if(1<a.version)return!1;l4(a);l4(a);l4(a);return!0},p4=function(){Q3.call(this)},vua=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ue=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3===p.nodeType)p=new N3(b,c,d,e.id,p.nodeValue,f||0<n,g.Nb(l)?void 0:l),m.push(p),e.o.push(p);else{var t={};g.Sa(t,l);vua(a,b,c,d,e,!0,p,t,m)}}},q4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},wua=function(a,b,c,d){d=Object.assign({Sj:0},d);
return new O3(a,b,c,"_"+P3++,d)},r4=function(a){g.A.call(this);
this.u=a;this.o=null},yua=function(a){var b={};
if(a=C3(a))b.lang=a,xua.test(a)&&(b.o=1);return b},u4=function(a){g.vL.call(this,a);
this.N=a;this.w=this.N.M();this.videoData=this.N.getVideoData();this.za=g.QK(this.N);this.A={Ab:{}};this.C={Ab:{}};this.P=[];this.T={};this.aa={};this.R=!1;this.oa=g.xL(this.videoData,this.N);this.Aa=!!this.videoData.captionTracks.length;this.Ca=!!this.videoData.Uk;this.ga="3"===this.w.controlsType;this.u=this.F=this.G=this.Z=this.ma=null;this.da=new r4(this.w);this.o=null;this.V=new g.Gr(this);var b=null,c=g.lo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Vn(c));this.ha=b;b=a.app.B;
c=!(!b||!b.Jm());this.va=!(!b||!b.dj());this.B=this.ga&&c&&!this.oa;this.I=!this.B&&this.ga&&this.va&&this.oa;g.B(this,this.da);this.B?this.ca=this.L=null:(this.L=new g.sn(this.FC,void 0,this),g.B(this,this.L),this.ca=new g.H(this.gO,2E3,this),g.B(this,this.ca));g.B(this,this.V);this.B||this.V.K(a,"resize",this.Tu);this.V.K(a,"onPlaybackAudioChange",this.lK);this.V.K(a,g.nC("captions"),this.uH,this);this.V.K(a,"crx_captions",this.vH,this);s4(this,t4(this,"display-settings")||{})},v4=function(a){if(1===
a.w.Yg||1===a.videoData.Yg||"alwayson"===g.CB(a.videoData,"yt:cc"))return!0;
if(2===a.w.Yg){var b=!!t4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().dr;return"ON"===c||"on"===g.CB(a.videoData,"yt:cc")},w4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Nn||"FORCED_ON"===c.dr},y4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Ca?!1:a.Aa?!1:!0);c=a.u.si(c);for(var d=[a.videoData.captionsLanguagePreference,a.w.captionsLanguagePreference,g.CB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(C3(c[f])===d[e])return c[f];return a.F&&a.F.sr?a.F.sr:(d=c.find(function(k){return k.isDefault}))?d:c[0]||x4(a)}return null},x4=function(a){return a.F&&a.F.Nn},z4=function(a){var b=x4(a);
return!!b&&a.o===b},zua=function(a,b){for(var c=a.N.app.B.sa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},B4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.R=c,a.R&&A4(a,"module-enabled",!!b));a.o=b;w4(a)&&(a.o=x4(a));a.load()},Aua=function(a,b){var c=a.za.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&xua.test(d)&&(b.params.o=1);d=a.za.getPlayerSize();switch(null!=b.params.Sj?b.params.Sj:1<b.o.length?1:0){case 1:return new L3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new M3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new K3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},s4=function(a,b,c){c=void 0===c?!1:c;
var d=C4.Ab;a.A={};g.Sa(a.A,C4);a.A.Ab={};g.Sa(a.A.Ab,d);a.C={Ab:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;V3.test(f);e.Ab.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;V3.test(f);e.Ab.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||C4.windowColor;V3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ab.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Ab.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Ue?3:d.bold?1:d.Ue?2:0);f=f.Ab;switch(e){case 1:f.bold=!0;delete f.Ue;break;case 2:delete f.bold;f.Ue=!0;break;case 3:f.bold=!0;f.Ue=!0;break;default:delete f.bold,delete f.Ue}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ab.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=C4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.A;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ab.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ab.fontFamily=f;a.loaded&&a.Tu();c&&A4(a,"display-settings",b)},Cua=function(a,b){if(b&&!a.G){var c=Zta({o:0,
lang:"de"});a.G=[c,new N3(c.start,c.end-c.start,0,c.id,"So werden die Untertitel mit der aktuellen Konfiguration aussehen.")];g.eL(a.player,a.G)}else!b&&a.G&&(Bua(a,a.G),a.G=null)},Bua=function(a,b){g.wT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.eb(this.P,c)},a);
a.L.Ua()},t4=function(a,b){if(!a.ha)return null;
try{var c=a.ha.get(b)}catch(d){a.ha.remove(b)}return c},A4=function(a,b,c){if(a.ha)try{a.ha.set(b,c)}catch(d){}};
g.ML.prototype.Vk=g.ca(11,function(){for(var a=g.be(document,"track",void 0,this.o),b=0;b<a.length;b++)g.ue(a[b])});
g.QL.prototype.Vk=g.ca(10,function(){this.o.Vk()});
g.ML.prototype.Jm=g.ca(9,function(){return!!this.o.textTracks});
g.QL.prototype.Jm=g.ca(8,function(){return this.o.Jm()});
g.ML.prototype.Qk=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.QL.prototype.Qk=g.ca(6,function(a){this.o.Qk(a)});
g.xC.prototype.dj=g.ca(5,function(){});
g.ML.prototype.dj=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.QL.prototype.dj=g.ca(3,function(){return this.o.dj()});
g.Xu.prototype.Zn=g.ca(1,function(a){return(a=this.mg(a))?a.o:0});
g.Gx.prototype.Zn=g.ca(0,function(){return 0});
var xua=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;Hta.prototype.si=function(a){return a?this.o.concat(this.u):this.o};
g.r(E3,g.A);g.h=E3.prototype;g.h.si=function(a){return this.u.si(a)};
g.h.Do=function(){};
g.h.Eo=function(){};
g.h.Mg=function(){};
g.h.Bj=function(){return""};
g.h.vB=function(){return!1};
g.h.X=function(){this.Mg();g.A.prototype.X.call(this)};
g.r(F3,E3);F3.prototype.Do=function(a,b,c){var d=this;this.ea();b=this.Bj(a,b);this.Mg();this.o=g.Eq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
F3.prototype.Eo=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
F3.prototype.Bj=function(a,b){var c=a.kc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.hl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=C3(a));return g.oq(c,d)};
F3.prototype.Mg=function(){this.o&&this.o.abort()};
G3.prototype.contains=function(a){a=g.qb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
G3.prototype.length=function(){return this.segments.length/2};
g.r(H3,g.A);g.h=H3.prototype;g.h.X=function(){g.A.prototype.X.call(this);this.u&&this.u.cancel()};
g.h.bB=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.Cb();var b=this.o;this.o=g.Wa(this.P.pg(a).o);b!==this.o&&this.G&&this.G()};
g.h.reset=function(){this.A=new G3;this.u&&(this.u.cancel(),this.u=null)};
g.h.uy=function(){this.ea();var a;if(a=null!=this.o)a=this.o,a=a.o.Cg(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.ih(),a.o[0].duration?(this.A.contains(a.o[0].u)||Kta(this,a),this.o=g.Wa(a.o)):!g.P(this.I.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.player.Cb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.F.start()};
g.r(I3,E3);g.h=I3.prototype;g.h.Do=function(a,b,c){var d=this;this.Mg();b=Mta(this,a.getId());b||(b=a.languageCode,b=this.ia.u?Nta(this,b,"386"):Nta(this,b));if(b){var e=1E3*(b.index.Zn(b.index.Qe())-b.index.gd(b.index.Qe()));this.o=new H3(new g.Iw,this.N,b,function(f,k){c(f,a,k,e)},this.B||g.gt(b.info),function(){d.o&&d.o.reset();
d.w=!0})}};
g.h.vB=function(){var a=this.w;this.w=!1;return a};
g.h.Eo=function(a){var b;this.B?b=[new g.Ss({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Ss({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ia.u?Lta(this,"386"):Lta(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
g.h.Mg=function(){this.o&&(this.o.dispose(),this.o=null)};
g.h.Bj=function(){return""};
g.r(J3,E3);J3.prototype.Do=function(a,b,c){var d=this;this.ea();b=this.Bj(a,b);this.Mg();this.o=g.Eq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
J3.prototype.Eo=function(a){var b=this,c=this.w,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.Ux&&(d.asrs=1);c=g.oq(c,d);this.Mg();this.o=g.Eq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),k=0;k<f.length;k++){var l=f[k],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),t=l.getAttribute("kind"),u=l.getAttribute("id"),z="true"===l.getAttribute("lang_default"),C="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");D3(b.u,new g.Ss({languageCode:m,languageName:n,name:p,kind:t,id:u,is_servable:!0,is_translateable:C,vss_id:l,is_default:z}))}e=e.getElementsByTagName("target");f=e.length;for(k=0;k<f;k++)m={languageCode:e[k].getAttribute("lang_code"),languageName:e[k].getAttribute("lang_translated"),languageOriginal:e[k].getAttribute("lang_original"),id:e[k].getAttribute("id"),isDefault:"true"===e[k].getAttribute("lang_default")},b.B[m.languageCode]=m.languageName,b.A.push(m)}a()},
withCredentials:!0})};
J3.prototype.Bj=function(a,b){var c=this.w,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=C3(a));return c=g.oq(c,d)};
J3.prototype.Mg=function(){this.o&&this.o.abort()};
var V3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Pta=["left","right","center","justify"];g.r(K3,g.R);g.h=K3.prototype;g.h.RK=function(a,b){var c=g.Jh(this.element,this.element.parentElement);this.ma=a-c.x;this.oa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.QK=function(a,b){var c=g.Oh(this.element),d=a-this.ma-.02*this.playerWidth,e=b-this.oa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Nd(f,0,2));var k=(e+c.height/2)/this.va*3;k=Math.floor(g.Nd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Nd(d,0,1);c=(e+k/2*c.height)/this.va;c=100*g.Nd(c,0,1);this.w.params.ag=l;this.w.params.Lg=c;this.w.params.Xe=d;this.u.ag=l;this.u.Lg=c;this.u.Xe=d;this.VB()};
g.h.OK=function(){g.En(this.element,"ytp-dragging")};
g.h.VB=function(){this.aj(this.C)};
g.h.aj=function(a){var b=Math.min(this.lx(),this.maxWidth),c=this.kx(),d="";3===this.w.params.o&&(d="rotate(180deg)");g.th(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Tq(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Xe+2;d=this.u.ag;switch(d){case 0:case 3:case 6:b=this.u.Ab.fontSizeIncrement;!g.P(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.o&&3!==this.u.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Lg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.th(this.element,a)};
g.h.Tq=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.T||this.C.length>b)b=0,this.T=!1,this.C=[],this.F=this.ca=this.V=null,g.se(this.B);for(;b<a.length;b++)Tta(this,a[b])};
g.h.lx=function(){return 0};
g.h.kx=function(){return 0};
g.h.toString=function(){return g.R.prototype.toString.call(this)};g.r(L3,K3);L3.prototype.Tq=function(a){var b=this.w.o;K3.prototype.Tq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Sa(d,c.o);g.Sa(d,Dua);var e=c.o;var f=d}Tta(this,c,d)}};
var Dua={RF:!0};g.r(M3,K3);g.h=M3.prototype;g.h.VB=function(){g.vn(this.da)};
g.h.LM=function(){g.En(this.element,"ytp-rollup-mode");this.aj(this.Ca,!0)};
g.h.kx=function(){return this.A?this.L:this.I};
g.h.lx=function(){return this.A?this.I:this.L};
g.h.aj=function(a,b){this.Ca=a;if(this.w.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.za=this.L;this.I=this.L=0;K3.prototype.aj.call(this,a);Yta(this,b);K3.prototype.aj.call(this,a)}else K3.prototype.aj.call(this,a)};g.r(N3,g.kC);N3.prototype.toString=function(){return g.kC.prototype.toString.call(this)};g.r(O3,g.kC);O3.prototype.toString=function(){return g.kC.prototype.toString.call(this)};
var P3=0;g.r(Q3,g.A);Q3.prototype.w=function(){return[]};
Q3.prototype.reset=function(){};g.r(R3,Q3);R3.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
R3.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Sa(l,this.A[m]);m=T3(c,"b");null!=m&&
(l.bold=m);m=T3(c,"i");null!=m&&(l.Ue=m);m=T3(c,"u");null!=m&&(l.underline=m);m=U3(c,"et");null!=m&&(l.charEdgeStyle=m);m=U3(c,"of");null!=m&&(l.offset=m);m=W3(c,"bc");null!=m&&(l.background=m);m=W3(c,"ec");null!=m&&(l.gr=m);m=W3(c,"fc");null!=m&&(l.color=m);m=U3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=S3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=S3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=S3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=U3(c,"rb");null!=m&&10!==m&&0!==m&&(l.Sb=
10<m?m-1:m);c=U3(c,"hg");null!=c&&(l.Rx=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.P[d]=bua(this,c);break;case "wp":d=c.getAttribute("id"),this.I[d]=cua(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=dua(this,d,e,!1);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!T3(d,
"a");n=(S3(d,"t")||0)+n;var p=S3(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var t=m?6:5,u=d.getAttribute("p");u=u?this.A[u]:null;var z=Array.from(d.childNodes);z.length&&(this.F=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var D=z[C],E=void 0;0<C&&(m=!0);var F=void 0;1===D.nodeType&&(F=D);if(F&&"s"===F.tagName){if((D=(D=F.getAttribute("p"))?this.A[D]:null)&&D.Sb&&(1===D.Sb?(D=z.slice(C,C+4),4===D.length&&
(E=aua(n,p,l,m,t,D,this.A),C+=3)):E=aua(n,p,l,m,t,[F],this.A)),!E){var I=F;E=n;F=p;D=l;var ia=m,pa=t,sc=I.textContent?I.textContent:"",md=I.getAttribute("p");md=md?this.A[md]:null;I=S3(I,"t")||0;E=new N3(E+I,F-I,pa,D,sc,ia,md)}}else E=new N3(n,p,t,l,D.textContent||"",m,u);k.push(E);this.u=E}if(0<k.length)for(k[0].windowId===this.B&&(this.o=dua(this,d,e,!0),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.o.push(k),c.push(k)}e=c}else e=[];return e};var Eua=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(X3,Q3);X3.prototype.reset=function(){this.u.clear()};
X3.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Ue=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(k.gr=Y3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!==
f.fcForeColor&&(k.color=Y3(f.fcForeColor));void 0!==f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(k.background=Y3(f.bcBackColor));void 0!==f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Sb=10<l?l-1:l,k.ff=Eua.get(k.Sb));f.hgHorizGroup&&(k.Rx=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!==
f.mhModeHint&&(k.Sj=f.mhModeHint),void 0!==f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(k.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(k.w=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(k.windowColor=Y3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),void 0!==f.ahHorPos&&(k.Xe=f.ahHorPos),
void 0!==f.apPoint&&(k.ag=f.apPoint),void 0!==f.avVerPos&&(k.Lg=f.avVerPos),void 0!==f.ccCols&&(k.Zg=f.ccCols),void 0!==f.rcRows&&(k.u=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=eua(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+P3++,l=eua(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,p=n?
6:5,t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var z=t[m],C=z.utf8;if(C){var D=z.tOffsetMs||0,E=null;z.pPenId&&(E=this.o.get(z.pPenId));if(2===(null!=l.params.Sj?l.params.Sj:1<l.o.length?1:0)&&n&&"\n"===C)continue;if(z=E&&1===E.Sb)if(z=m,z+3>=t.length||!t[z+1].pPenId||!t[z+2].pPenId||!t[z+3].pPenId)z=!1;else{var F=t[z+1].pPenId;(F=this.o.get(F))&&F.Sb&&2===F.Sb?(F=t[z+2].pPenId,F=this.o.get(F),!F||!F.Sb||3>F.Sb?z=!1:(F=t[z+3].pPenId,z=(F=this.o.get(F))&&F.Sb&&2===F.Sb?
!0:!1)):z=!1}if(z){D=t[m+1].utf8;z=t[m+3].utf8;F=t[m+2].utf8;var I=this.o.get(t[m+2].pPenId);C=$ta(C,D,F,z,I);n=new N3(e,f,p,k,C,n,E);m+=3}else n=new N3(e+D,f-D,p,l.id,C,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};$3.prototype.clear=function(){this.w=this.time=this.mode=0;this.o=[];this.reset()};
$3.prototype.reset=function(){this.mode=0;this.A.reset(0);this.B.reset(1)};
var fua=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];a4.prototype.set=function(a){this.type=a};
a4.prototype.get=function(){return this.type};
b4.prototype.clear=function(){this.state=0};
b4.prototype.update=function(){this.state=2===this.state?1:0};
b4.prototype.isValid=function(){return 0!==this.state};
b4.prototype.matches=function(a,b){return this.isValid()&&a===this.bi&&b===this.Vg};
kua.prototype.reset=function(){this.timestamp=this.o=0};
c4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
c4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
c4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var lua=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],mua=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],nua=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],oua=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];i4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.A=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Z3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};tua.prototype.B=function(){};g.r(k4,tua);k4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+P3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new O3(c,d-c,5,f,{textAlign:0,ag:0,Xe:2.5*b,Lg:5.33*a});e=new N3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(n4,Q3);n4.prototype.w=function(a){a=new k4(a,a.byteLength,this.u);if(uua(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.A=m4(a)*(1E3/45):1===a.version&&(a.A=4294967296*m4(a)+m4(a)),a.C=l4(a);0<a.C;a.C--){var b=l4(a),c=l4(a),d=l4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,ow:c,pw:d,order:b.o.length}))}jua(this.o,a);return a.w}return[]};
n4.prototype.reset=function(){this.o.clear()};g.r(p4,Q3);
p4.prototype.w=function(a,b){for(var c=[],d=a.split(Fua),e=1;e<d.length;e++){var f=d[e],k=b;if(""!==f&&!Gua.test(f)){var l=D4.exec(f);if(l&&4<=l.length){var m=q4(l[1]),n=q4(l[2])-m;m+=k;var p=(l=l[3])?l.split(" "):[];l={};var t=null,u="",z=null,C="";l.textAlign=2;p=g.q(p);for(var D=p.next();!D.done;D=p.next())if(D=D.value.split(":"),2===D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(t=D[0],l.Lg=Number.parseInt(t,10),2===D.length&&(u=D[1].trim()));break;case "position":D=
E.split(",");z=D[0];l.Xe=Number.parseInt(z,10);2===D.length&&(C=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}t||(l.Lg=100,u||(u="end"));if(!z)switch(l.textAlign){case 0:l.Xe=0;break;case 1:l.Xe=100;break;default:l.Xe=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(C){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.ag=0>t||8<t?7:t;f=f.substring(D4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");C=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))k=wua(m,n,5,C),n=new N3(m,n,5,k.id,l,!1,g.Nb(f)?void 0:f),c.push(k),c.push(n),k.o.push(n);else for(u=l.split(Hua),1===u.length?(l=5,C=wua(m,n,l,C)):(t=l=6,C=Object.assign({Zg:32},C),C=new O3(m,n,t,"_"+P3++,C)),c.push(C),t=m,z=0;z<u.length;z++)p=u[z],0===z%2?(D=g.C1("<html>"+p+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(p))):E=D.firstChild,vua(this,t,n-(t-m),l,C,0<z,E,f,c)):t=q4(p)+k}D4.lastIndex=0}}return c};
var Gua=/^NOTE/,Fua=/(?:\r\n|\r|\n){2,}/,D4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Hua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(r4,g.A);r4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
r4.prototype.reset=function(){this.o&&this.o.reset()};
r4.prototype.X=function(){g.A.prototype.X.call(this);this.clear()};var C4={windowColor:"#080808",windowOpacity:0,textAlign:2,ag:7,Xe:50,Lg:100,Ab:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(u4,g.vL);g.h=u4.prototype;g.h.X=function(){if(this.B||this.I){var a=this.N.app.B;a&&!a.ea()&&a.Vk()}else Cua(this,!1);g.vL.prototype.X.call(this)};
g.h.load=function(){var a=this;g.vL.prototype.load.call(this);var b=!g.P(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u)this.o&&(this.da.clear(),this.B?zua(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Do(this.o,"json3",function(d,e,f,k){if(d){a.u.vB()&&(a.P=[],g.hR(a.N.app,"captions",void 0),a.L.Ua(),a.da.reset());var l=a.da;f=f||0;k=k||0;if(l.u.fa("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.mv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),o4(d)||(d=Gta(new Uint8Array(d))))}}else"string"===typeof d||o4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.mv(m,0,1835295092))&&m.size?Gta(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,t=k;if(!o4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new n4(t,e));var u=l.o.w(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,t=f,l.o||(l.o=new p4),p=l.o.w(e,t),.01>Math.random()&&g.Uq(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.o||(l.o=new X3(yua(e)));n=l.o.w(p,f);break b}catch(I){g.Tq(I);n=[];break b}t=g.C1(p);if(!t||!t.firstChild){var z=Error("Invalid caption track data");z.params=p;throw z;}if("timedtext"===t.firstChild.tagName){if(3===Number(t.firstChild.getAttribute("format"))){l.o||(l.o=new R3(yua(e),l.u));n=l.o.w(t,f);break b}var C=Error("Unsupported subtitles format in web player (Format2)");
C.params=p;throw C;}if("transcript"===t.firstChild.tagName){var D=Error("Unsupported subtitles format in web player (Format1)");D.params=p;throw D;}var E=Error("Invalid caption track data");E.params=p;throw E;}u=n}var F=u}catch(I){g.Tq(I),l.clear(),F=[]}else F=[];g.eL(a.player,F);!a.R||a.I||z4(a)||g.$y(a.w)||g.az(a.w)||(a.ca.Pe(),F=Zta({ag:0,Xe:5,Lg:5,u:2,textAlign:0,o:0,lang:"de"}),a.Z=[F],l=["Klicke auf ",", um die Einstellungen aufzurufen."],a.ma||(u=new g.Mu(g.VM()),g.B(a,u),a.ma=u.element),u=
F.end-F.start,(e=g.Ts(a.o))&&a.Z.push(new N3(F.start,u,0,F.id,e)),a.Z.push(new N3(F.start,u,0,F.id,l[0]),new N3(F.start,u,0,F.id,a.ma,!0),new N3(F.start,u,0,F.id,l[1],!0)),g.eL(a.player,a.Z),a.ca.Ua());!a.R||a.I||z4(a)||(A4(a,"module-enabled",!0),a.F&&(a.F.o=a.o),(F=g.W(a.player.app))&&g.RH(F.B));a.R=!1}}),!b||this.B||this.I||z4(this)||this.player.na("captionschanged",B3(this.o))),b||(this.o&&!z4(this)?this.player.na("captionschanged",B3(this.o)):this.player.na("onCaptionsTrackListChanged"));
else{var c;this.oa?c=new I3(this.videoData.ia,this.player):this.Aa?c=new F3(this.w,this.videoData,this.player.getAudioTrack()):c=new J3(this.videoData.Uk,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.w.captionsLanguagePreference||g.CB(this.videoData,"yt:cc_default_lang")||this.w.Jc,this.videoData.Zq,this.w);this.u=c;g.B(this,this.u);c.Eo(function(){var d;a.R||v4(a)?d=y4(a,a.R):w4(a)&&(d=x4(a));if(a.B||a.I){for(var e=a.u.si(!0),f=[],k=0;k<e.length;k++){var l=e[k],m=g.oe("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.Ts(l));m.setAttribute("srclang",C3(l));m.setAttribute("id",l.toString());a.I||m.setAttribute("src",a.u.Bj(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.N.app.B;d.Qk(f);f=d.sa();a.va&&a.V.K(f.textTracks,"change",a.pN)}else!a.o&&d&&B4(a,d),a.player.na("onCaptionsTrackListChanged"),a.player.na("onApiChange")})}};
g.h.unload=function(){this.B&&this.o?zua(this,!1):(this.ca&&this.ca.Pe(),g.hR(this.player.app,"captions",void 0),this.P=[],this.u&&this.u.Mg(),this.da.clear(),this.G&&g.eL(this.player,this.G),this.Tu());g.vL.prototype.unload.call(this);var a=g.W(this.player.app);a&&g.RH(a.B);this.player.na("captionschanged",{})};
g.h.create=function(){(this.ga?this.B||this.I:w4(this)||v4(this))&&this.load()};
g.h.getTrackById=function(a){for(var b=this.u.si(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.h.pN=function(){for(var a=this.N.app.B.sa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&B4(this,b,!0)};
g.h.UO=function(){!this.o&&this.B||this.unload()};
g.h.uH=function(a){this.P.push(a);this.L.Ua()};
g.h.vH=function(a){g.eb(this.P,a);this.u instanceof I3&&this.u.B&&g.wT(this.player.app,[a],void 0);this.L.Ua()};
g.h.YN=function(a){if(a instanceof O3){var b=this.T[a.id];b&&b.w!==a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=Aua(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.gO=function(){Bua(this,this.Z);this.Z=null};
g.h.FC=function(){this.L.stop();g.Ob(this.aa);this.P.sort(g.mC);var a=this.P;if(this.G){var b=(0,g.ve)(a,function(c){return-1===this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.YN,this);g.zb(this.T,function(c,d){this.aa[d]?(c.element.parentNode||g.iL(this.player,c.element,4),c.aj(this.aa[d])):(c.dispose(),delete this.T[d])},this)};
g.h.nO=function(){s4(this,{},!0);g.P(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.na("captionssettingschanged")};
g.h.gF=function(){var a=C4.Ab;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ue?3:a.bold?1:a.Ue?2:0,textOpacity:a.textOpacity,windowColor:C4.windowColor,windowOpacity:C4.windowOpacity};var b=t4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.LC=function(a,b){var c={};g.Sa(c,t4(this,"display-settings"));g.Sa(c,a);s4(this,c,b);this.player.na("captionssettingschanged")};
g.h.Tu=function(){!this.B&&this.loaded&&(g.zb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.FC())};
g.h.Pc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Nd(b,-2,4);this.LC({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&B4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.w.w&&A4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Oa(b))break;if(g.Nb(b)){B4(this,null,!0);break}for(var d=this.u.si(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
Fta(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||B4(this,c,!0)}else return this.loaded&&this.o&&!z4(this)?B3(this.o):{};return"";case "tracklist":return this.u?(0,g.Dc)(this.u.si(!(!b||!b.includeAsr)),function(k){return B3(k)}):[];
case "translationLanguages":return this.u?this.u.A.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0===b||Cua(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.w&&a.push("stickyLoading");return a};
g.h.BG=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.h.OO=function(){this.loaded&&this.o&&!z4(this)?(A4(this,"module-enabled",!1),this.unload(),w4(this,!0)&&B4(this,x4(this),!1)):B4(this,z4(this)||!this.o?y4(this,!0):this.o,!0)};
g.h.lK=function(){var a=z4(this);w4(this,a)?B4(this,this.player.getAudioTrack().Nn,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.ga?this.B||this.I:w4(this)||v4(this))&&(a?B4(this,y4(this),!1):this.load()))};g.KL.captions=u4;})(_yt_player);
